BEGIN;

DROP TABLE IF EXISTS group_payment CASCADE;
DROP TABLE IF EXISTS group_expense_user CASCADE;
DROP TABLE IF EXISTS group_expense CASCADE;
DROP TABLE IF EXISTS group_user CASCADE;
DROP TABLE IF EXISTS "group" CASCADE;
DROP TABLE IF EXISTS users CASCADE;

DROP TABLE IF EXISTS migrations;
DROP TYPE IF EXISTS group_status;

INSERT INTO migrations (code)
VALUES ('U110120261827__base_structure');

COMMIT;
